### PR TITLE
Removed mention of "meth" namespace, added pubDate

### PR DESCRIPTION
**Pull request by justgo129**

### CODE REVIEW

**Comment by justgo129** [comment]
Resolves https://github.com/USGCRP/gcis-ontology/issues/9

**Comment by bduggan** [comment]
Check the build log -- looks like invalid turtle.

**Comment by justgo129** [comment]
Oops, that comma should have been a semicolon.  Thanks for the pointer.

**Comment by justgo129** [comment]
Resolves https://github.com/USGCRP/gcis-ontology/issues/9

**Comment by justgo129** [comment]
dwc:year -> dbpprop:pubDate addresses https://github.com/USGCRP/gcis-ontology/issues/33

**Pull request merged**
