### PR TITLE
prov:wasDerivedFrom->cito:cites

### PR DESCRIPTION
**Pull request by justgo129**
to be consistent with terminology in the html.

### CODE REVIEW

**Comment by bduggan** [comment]
Could you give an example of a page that should have cites instead of derivedFrom?  I'm getting confused by this template: I think we need some unit tests to accompany this change.

**Comment by justgo129** [comment]
Sure.  Let's take a look at:
http://data.globalchange.gov/report/usgcrp-ngcrp2012-2021

Note the myriad instances of "This report cites..."
However, in the turtle:
http://data.globalchange.gov/report/usgcrp-ngcrp2012-2021.thtml
most of these are prefixed by "prov:wasDerivedFrom" in-lieu of "cito:cites"

**Comment by bduggan** [comment]
I'm not sure this change does what you want.

Look at the "prov" tab on stage -- for most of these,
the "cites" relationship comes from the database, not
the template.

'prov.ttl.tut' is included in many other other templates
so this will change "derivedFrom" to "cites" in many places.

We need some tests.

**Comment by justgo129** [comment]
Ah, makes sense.  I'm closing this ticket, #222 then.

**Pull request closed without merging**
