### PR TITLE
Added "unit of" as relationship type

### PR DESCRIPTION
**Pull request by justgo129**
I forgot to add it in #361.

### CODE REVIEW

**Comment by justgo129** [comment]
@lomky I think this should work for now.  Let's see what the SPARQL output is and then we can update the code accordingly in case we recharacterize.

**Comment by lomky** [comment]
@justgo129 I noticed a typo on line 26, "branch_of" has two underscores instead of one.

**Comment by justgo129** [comment]
@lomky we should be good to go.

**Comment by justgo129** [comment]
Thanks, @lomky.  @zednis this also resolves #351.

**Pull request merged**
