### PR TITLE
update datacite:AlternateResourceIdentifier usage

### PR DESCRIPTION
**Pull request by zednis**
based on http://www.essepuntato.it/lode/http://purl.org/spar/datacite#introduction the property to reference a datacite:AlternateResourceIdentifier would be datacite:hasIdentifier.

We can optionally include a datacite:usesIdentifierScheme here if one is known.

### CODE REVIEW

**Comment by justgo129** [comment]
Is datacite:hasIdentifier related to dcterms:identifier, which we use for non-datasets?

**Comment by zednis** [comment]
No formal relationship that I saw.

dcterms:identifier has a Literal for a range.

datacite:hasIdentifier is an object property so it references a resource that can additional type information or attributes.

**Comment by justgo129** [comment]
Team, would it be all right if we use a particular term for "identifier" for datasets only (i.e. should we need one for journals, reports, etc.)?  The bibo ontology uses dcterms:identifier for those elements.  I am fine with using a different term for datasets only but am curious what everyone else thinks.

With regard to the specific discussion, yes, I am fine with substituting datacite:hasIdentifier for dcterms:identifier for datasets.

**Comment by bduggan** [comment]
Looks good, thanks.

**Pull request merged**
