### PR TITLE
Updated ex. 2 so it works

### PR DESCRIPTION
**Pull request by justgo129**
Addresses https://github.com/USGCRP/gcis-ontology/issues/121

### CODE REVIEW

**Comment by justgo129** [comment]
It's an expanded version of "List  all findings from the National Climate Assessment" example at:
https://data.globalchange.gov/examples

**Comment by bduggan** [comment]
This is too long for an example, The examples page needs a few concise queries that won't scare people off.

**Comment by justgo129** [comment]
Point well taken.  @zednis @xgmachina @lic10 could one of you nonetheless please add the commits from #233 and #234 to the test suite?

**Comment by bduggan** [comment]
I'm closing this, it's been resolved elsewhere.

**Pull request closed without merging**
