### PR TITLE
checks for values for software and methodology

### PR DESCRIPTION
**Pull request by zednis**
Checks for software and methodology values before creating of PROV qualified association and plan relationships.

### CODE REVIEW

**Comment by bduggan** [comment]
Unfortunately, this would exclude activities for which there is a value for methodology but there is not a value for software.
There actually are cases like this: http://data.globalchange.gov/activity/14d6d5e3-ncdc-gst-anomalies-process

**Comment by zednis** [comment]
In PROV a plan is a description of the actions or steps adopted by the agent in the context of the activity.  PROV does not include the ability to related a plan directly to an activity without there being an associated agent.

We could have additional agents associated with the activity. The agent could be a person, organization, or software agent.  We could also consider having generic default agents such as "analysis software" for cases were detailed information is not available.
 
If the methodology is really just a description of the activity then we could change our modeling so the methodology is not a PROV plan.

**Comment by zednis** [comment]
In the example link you provided the agent would be the "kunkle2.pro" IDL program.

Also, the dbpedia_owl:filename value seems incorrect.

```
## Output datafiles   
   dbpedia_owl:filename "kunkle2.pro \r\nmain IDL program that produces the figure\r\nUses both author-written code and IDL built-in functionality to process the data and display the results.\r\n\r\nmlost.gridded.v3.5.3.201306.bin\r\n  (input; binary MLOST data file obtained from ftp://ftp.ncdc.noaa.gov/pub/data/mlost/operational/ on 2013-07-31 09:39:34)\r\n\r\nread_mlost_monthly_grids.pro\r\nIDL subroutine that reads the original monthly MLOST data.\r\nCalled by compute_mlost_annual_grids\r\n\r\ncompute_mlost_annual_grids.pro\r\nIDL subroutine for computing annual anomalies from monthly anomalies.\r\nRequires at least 10 non-missing monthly values to compute an annual mean.\r\nCalled by mlost_mly2ann_grid\r\n\r\nmlost_mly2ann_grid.pro\r\nIDL subroutine that calls compute_mlost_annual_grids\r\nWrites the annual anomalies to an output file (ann_mlost.gridded.v3.5.3.201306.bin).\r\nCalled by kunkle2\r\n\r\nann_mlost.gridded.v3.5.3.201306.bin\r\nannual anomaly data file written by subroutine mlost_mly2ann_grid\r\ncompute_trends_from_annual_mlost.pro\r\nReads annual anomaly data file ann_mlost.gridded.v3.5.3.201306.bin\r\nComputes temperature trends over the period 1900-2012 in each grid box with enough available data\r\nUses method of standard least squares straight line fit with equal weighting per annual anomaly\r\nRequires at least 75% non-missing data in the period 1900-2012 in order to compute a trend\r\nThere must also be at least some non-missing data in the first and last two 10% segments of the trend-period time series\r\nCalled by kunkel2\r\n\r\ndct_blue2red.pro\r\nIDL function that defines the colors used in displaying the trends on the map\r\nCalled by kunkel2"^^xsd:string;
```

**Comment by bduggan** [comment]
On Monday, June  1, Stephan Zednik wrote: 
> We could have additional agents associated with the activity. The agent could be a person, organization, or software agent.  We could also consider having generic default agents such as "analysis software" for cases were detailed information is not available.
>  

This sounds good, perhaps just an unlabeled node?  (i.e.
to allow for cases in which there is an agent, but the details
are not available, but it might not be software)

**Comment by zednis** [comment]
I think a default node makes sense.  It could be a blank node.  I am not sure if we want to leave it unlabeled. 

Should the default agent show in interfaces and if so what should it show?

I'll update the pull request.  Don't merge it yet.

**Comment by rewolfe** [comment]
In this case, there is no output file.  It looks like there are two files
mentioned in the method:

  input file -
ftp://ftp.ncdc.noaa.gov/pub/data/mlost/operational/mlost.gridded.v3.5.3.201306.bin
- obtained on 2013-07-31 09:39:34

  intermediate file - ann_mlost.gridded.v3.5.3.201306.bin

I think that the IDL function actually writes to the screen and then the
the user probably saves the screen shot as the png file from the figure:
caq_temp_trends_mlost_1900-2012_v2.png
<http://data.globalchange.gov/file/5758d48c-38de-4518-bd9a-46adc036eab3>

On Mon, Jun 1, 2015 at 2:40 PM, Stephan Zednik <notifications@github.com>
wrote:

> I think a default node makes sense. It could be a blank node. I am not
> sure if we want to leave it unlabeled.
>
> Should the default agent show in interfaces and if so what should it show?
>
> I'll update the pull request. Don't merge it yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/pull/159#issuecomment-107666625>.
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by bduggan** [comment]
On Monday, June  1, Stephan Zednik wrote: 
> I think a default node makes sense.  It could be a blank node.  I am not sure if we want to leave it unlabeled. 

Okay.  I don't know the difference between those two things..

> Should the default agent show in interfaces and if so what should it show?

I would say no; I can't picture a situation in which it be
better to have a default agent show up.

> I'll update the pull request.  Don't merge it yet.

Okay.

Brian

**Comment by zednis** [comment]
> On Jun 1, 2015, at 12:53 PM, Brian Duggan <notifications@github.com> wrote:
> 
> On Monday, June 1, Stephan Zednik wrote: 
> > I think a default node makes sense. It could be a blank node. I am not sure if we want to leave it unlabeled. 
> 
> Okay. I don't know the difference between those two things..

Ah. I interpret an unnamed name as a bnode (no URI) but an unlabled node as a resource with to rdfs:label (or equivalent)

named node = node with URI
labeled node = node with label property (used by display interfaces)

- Stephan

**Comment by bduggan** [comment]
On Monday, June  1, Stephan Zednik wrote: 
> > On Monday, June 1, Stephan Zednik wrote: 
> > > I think a default node makes sense. It could be a blank node. I am not sure if we want to leave it unlabeled. 
> > 
> > Okay. I don't know the difference between those two things..
> 
> Ah. I interpret an unnamed name as a bnode (no URI) but an unlabled node as a resource with to rdfs:label (or equivalent)
> 
> named node = node with URI
> labeled node = node with label property (used by display interfaces)

Given that the agent may be different for every activity, sounds like
maybe we need to use a bnode?

Brian

**Comment by zednis** [comment]
I agree a bnode makes sense.  If we aren’t showing anything about the agent in a display interface we shouldn’t have to add a label.

I think we can get by with just

```
prov:agent [ a prov:Agent ] ;
```

Stephan

**Comment by rewolfe** [comment]
This is somewhat confusing because in GCIS, there are three activities that
are related to this figure.  Two of which appear to be old/redundant
because they are not associated with an image or dataset:

http://data.globalchange.gov/activity/14d6d5e3-ncdc-gst-anomalies-process -
redundant

http://data.globalchange.gov/activity/14d6d5e3-nca3-ncdc-gst-anomalies-process
- redundant

http://data.globalchange.gov/activity/14d6d5e3-nca3-ncdc-gst-anomalies-r201307-process
- good!

Speculation: This may have happened when drafts of these activities were
entered before the NCA3 release.  We should probably check for similar
redundant activities.

On Mon, Jun 1, 2015 at 3:43 PM, Stephan Zednik <notifications@github.com>
wrote:

> I agree a bnode makes sense. If we aren’t showing anything about the agent
> in a display interface we shouldn’t have to add a label.
>
> I think we can get by with just
>
> ```
> prov:agent [ a prov:Agent ] ;
> ```
>
> Stephan
>
> > On Jun 1, 2015, at 1:07 PM, Brian Duggan <notifications@github.com>
> wrote:
> >
> > On Monday, June 1, Stephan Zednik wrote:
> > > > On Monday, June 1, Stephan Zednik wrote:
> > > > > I think a default node makes sense. It could be a blank node. I am
> not sure if we want to leave it unlabeled.
> > > >
> > > > Okay. I don't know the difference between those two things..
> > >
> > > Ah. I interpret an unnamed name as a bnode (no URI) but an unlabled
> node as a resource with to rdfs:label (or equivalent)
> > >
> > > named node = node with URI
> > > labeled node = node with label property (used by display interfaces)
> >
> > Given that the agent may be different for every activity, sounds like
> > maybe we need to use a bnode?
> >
> > Brian
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/USGCRP/gcis/pull/159#issuecomment-107673410>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/pull/159#issuecomment-107681732>.
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by rewolfe** [comment]
For "prov:agent [ a prov:Agent ]" why don't we use something like this:
"prov:softwareAgent [ a prov:SoftwareAgent
<http://www.w3.org/TR/2013/REC-prov-o-20130430/#SoftwareAgent> ]"?

On Mon, Jun 1, 2015 at 4:07 PM, Robert Wolfe <rewolfe@usgcrp.gov> wrote:

> This is somewhat confusing because in GCIS, there are three activities
> that are related to this figure.  Two of which appear to be old/redundant
> because they are not associated with an image or dataset:
>
> http://data.globalchange.gov/activity/14d6d5e3-ncdc-gst-anomalies-process
> - redundant
>
>
> http://data.globalchange.gov/activity/14d6d5e3-nca3-ncdc-gst-anomalies-process
> - redundant
>
>
> http://data.globalchange.gov/activity/14d6d5e3-nca3-ncdc-gst-anomalies-r201307-process
> - good!
>
> Speculation: This may have happened when drafts of these activities were
> entered before the NCA3 release.  We should probably check for similar
> redundant activities.
>
> On Mon, Jun 1, 2015 at 3:43 PM, Stephan Zednik <notifications@github.com>
> wrote:
>
>> I agree a bnode makes sense. If we aren’t showing anything about the
>> agent in a display interface we shouldn’t have to add a label.
>>
>> I think we can get by with just
>>
>> ```
>> prov:agent [ a prov:Agent ] ;
>> ```
>>
>> Stephan
>>
>> > On Jun 1, 2015, at 1:07 PM, Brian Duggan <notifications@github.com>
>> wrote:
>> >
>> > On Monday, June 1, Stephan Zednik wrote:
>> > > > On Monday, June 1, Stephan Zednik wrote:
>> > > > > I think a default node makes sense. It could be a blank node. I
>> am not sure if we want to leave it unlabeled.
>> > > >
>> > > > Okay. I don't know the difference between those two things..
>> > >
>> > > Ah. I interpret an unnamed name as a bnode (no URI) but an unlabled
>> node as a resource with to rdfs:label (or equivalent)
>> > >
>> > > named node = node with URI
>> > > labeled node = node with label property (used by display interfaces)
>> >
>> > Given that the agent may be different for every activity, sounds like
>> > maybe we need to use a bnode?
>> >
>> > Brian
>> >
>> > —
>> > Reply to this email directly or view it on GitHub <
>> https://github.com/USGCRP/gcis/pull/159#issuecomment-107673410>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGCRP/gcis/pull/159#issuecomment-107681732>.
>>
>
>
>
> --
> Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by zednis** [comment]
> On Jun 1, 2015, at 14:25, Robert Wolfe <notifications@github.com> wrote:
> 
> For "prov:agent [ a prov:Agent ]" why don't we use something like this:
> "prov:softwareAgent [ a prov:SoftwareAgent
> <http://www.w3.org/TR/2013/REC-prov-o-20130430/#SoftwareAgent> ]"?

1) The property prov:softwareAgent does not exist
2) This is not valid RDF

- Stephan

>

**Comment by bduggan** [comment]
On Monday, June  1, Robert Wolfe wrote: 
> This is somewhat confusing because in GCIS, there are three activities that
> are related to this figure.
> [..]

This is not relevant: all of these have a methodology but no software.

Brian

**Comment by rewolfe** [comment]
Okay.  So, why not "prov:agent [ a prov:SoftwareAgent ]" ?  Isn't
prov:SoftwareAgent is a subclass of prov:Agent?

By the way, a RDF 101 question (sorry for being so slow) : What do you mean
by this:

   prov:agent [ a prov:Agent ]

On Mon, Jun 1, 2015 at 4:49 PM, Brian Duggan <notifications@github.com>
wrote:

> On Monday, June 1, Robert Wolfe wrote:
> > This is somewhat confusing because in GCIS, there are three activities
> that
> > are related to this figure.
> > [..]
>
> This is not relevant: all of these have a methodology but no software.
>
> Brian
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/pull/159#issuecomment-107702678>.
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by zednis** [comment]
--Stephan

> On Jun 1, 2015, at 15:06, Robert Wolfe <notifications@github.com> wrote:
> 
> Okay. So, why not "prov:agent [ a prov:SoftwareAgent ]" ? Isn't
> prov:SoftwareAgent is a subclass of prov:Agent?

If we want to state that the agent is always a software agent we can use this.

> 
> By the way, a RDF 101 question (sorry for being so slow) : What do you mean
> by this:
> 
> prov:agent [ a prov:Agent ]

prov:agent is the property used with an Association resource to reference the agent associated with the activity.  prov:Agent is the type of the agent; in this example we are simply being general with the type of the agent.  We could use any subclass of prov:Agent here, such as prov:Person, prov:Organization, or prov:SoftwareAgent.  We could even omit explicitly declaring a prov type here (A reasoner would infer this resource to include type prov:Agent in that case).

The [ ] signifies a blank node.  In this case we are saying that there is an agent (type prov:Agent) associated with the activity - and that is all.  We are not describing the agent further or giving it a URI.

Stephan

**Comment by bduggan** [comment]
On Monday, June  1, Stephan Zednik wrote: 
> > prov:agent [ a prov:Agent ]
> 
> prov:agent is the property used with an Association resource to reference the agent associated with the activity.  prov:Agent is the type of the agent; in this example we are simply being general with the type of the agent.  We could use any subclass of prov:Agent here, such as prov:Person, prov:Organization, or prov:SoftwareAgent.  We could even omit explicitly declaring a prov type here (A reasoner would infer this resource to include type prov:Agent in that case).
> 
> The [ ] signifies a blank node.  In this case we are saying that there is an agent (type prov:Agent) associated with the activity - and that is all.  We are not describing the agent further or giving it a URI.
> 

Thanks for this explanation.  I found it instructive to convert to ntriples:

```
    @prefix prov: <http://www.w3.org/ns/prov#> .

    <http://example.com/fortan_program>
        prov:agent [ a prov:Agent ] .

    $ rapper -i turtle -o ntriples agent.ttl

    _:genid1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Agent> .
    <http://example.com/fortan_program> <http://www.w3.org/ns/prov#agent> _:genid1 .
    rapper: Parsing returned 2 triples
```

Brian

**Comment by rewolfe** [comment]
Stephan, Thanks for the explanation.  Brian, Thanks for the example.  Now I
understand.

On Tue, Jun 2, 2015 at 8:25 AM, Brian Duggan <notifications@github.com>
wrote:

> On Monday, June 1, Stephan Zednik wrote:
> > > prov:agent [ a prov:Agent ]
> >
> > prov:agent is the property used with an Association resource to
> reference the agent associated with the activity. prov:Agent is the type of
> the agent; in this example we are simply being general with the type of the
> agent. We could use any subclass of prov:Agent here, such as prov:Person,
> prov:Organization, or prov:SoftwareAgent. We could even omit explicitly
> declaring a prov type here (A reasoner would infer this resource to include
> type prov:Agent in that case).
> >
> > The [ ] signifies a blank node. In this case we are saying that there is
> an agent (type prov:Agent) associated with the activity - and that is all.
> We are not describing the agent further or giving it a URI.
> >
>
> Thanks for this explanation. I found it instructive to convert to ntriples:
>
> ```
> @prefix prov: <http://www.w3.org/ns/prov#> .
>
> <http://example.com/fortan_program>
> prov:agent [ a prov:Agent ] .
>
> $ rapper -i turtle -o ntriples agent.ttl
>
> _:genid1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <
> http://www.w3.org/ns/prov#Agent> .
> <http://example.com/fortan_program> <http://www.w3.org/ns/prov#agent>
> _:genid1 .
> rapper: Parsing returned 2 triples
> ```
>
> Brian
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/pull/159#issuecomment-107936442>.
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Pull request merged**
