### PR TITLE
dcterms:SizeOrDuration -> dcterms:extent

### PR DESCRIPTION
**Pull request by zednis**
Fixes USGCRP/gcis-ontology/issues/8

based on RDF publishing guidelines from http://wiki.dublincore.org/index.php/User_Guide/Publishing_Metadata#dcterms:extent

### CODE REVIEW

**Comment by justgo129** [comment]
Works for me.

**Comment by justgo129** [comment]
I think it's failing because we'll need to declare the prefix rdf in that template.

**Comment by zednis** [comment]
Thanks.  I attempted to add the rdf prefix but I am not sure if I did it correctly.

**Comment by bduggan** [comment]
Yep, looks good!

**Comment by justgo129** [comment]
Works for me.

**Pull request merged**
