### PR TITLE
moved location of the org for consistency with other entries

### PR DESCRIPTION
**Pull request by justgo129**

### CODE REVIEW

**Comment by justgo129** [comment]
rationale: Allow structured entries for contributors to show up--in an identical location within the page--in the GCIS pages describing datasets,  Added data_producer to the list of contributors that can come up on that page.

**Comment by justgo129** [comment]
Merged #277.

**Comment by rewolfe** [comment]
@justgo129 - This change #277 failed the Travis tests.

**Comment by justgo129** [comment]
@rewolfe I'm not clear as to the meaning of the error message:
https://travis-ci.org/USGCRP/gcis/jobs/104146498

$ cd USGCRP/gcis
7.42s$ git fetch origin +refs/pull/277/merge:
fatal: Couldn't find remote ref refs/pull/277/merge
Unexpected end of command stream
The command "eval git fetch origin +refs/pull/277/merge:" failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/277/merge
Unexpected end of command stream
The command "eval git fetch origin +refs/pull/277/merge:" failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/277/merge
Unexpected end of command stream
The command "eval git fetch origin +refs/pull/277/merge:" failed 3 times.

**Pull request merged**
