### PR TITLE
Front page styling, including svg edits

### PR DESCRIPTION
**Pull request by tsizer**

### CODE REVIEW

**Comment by bduggan** [comment]
Looks good, though I think maybe the top should not be blue, since it makes it look like it is a link.

**Comment by tsizer** [comment]
I just tried something other than black, since Steve commented on that.  Could be a different color, or maybe a darker blue.

**Comment by tsizer** [comment]
Hi Brian,

Have you gotten any other feedback?   Should I go ahead and try making the
blue title (spellout) a darker blue?  Also, I think the H2s, "About",
"Examples", are a bit too big.  Please let me know.

Other than that, I do have some work that needs to be done on the
usclivar.org website this week.  I'll work on the report templates for
gcis, but won't be spending more than a couple of hours per day this week.

Thanks,

Tania

On Fri, Jan 23, 2015 at 6:14 PM, Brian Duggan <notifications@github.com>
wrote:

> Looks good, though I think maybe the top should not be blue, since it
> makes it look like it is a link.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/pull/101#issuecomment-71292942>.
>



-- 
________________
*Tania Sizer*
Web Developer
UCAR/JOSS
P.O. Box 3000
Boulder, CO 80307
303-497-8684
tsizer@ucar.edu


*Joint Office for Science Supportwww.joss.ucar.edu
<http://www.joss.ucar.edu> *

**Comment by bduggan** [comment]
Hi Tania,

Sure, please go ahead and make color and font adjustments however you think is appropriate, I'll plan to push this out later this week.  (and ask for feedback at the same time)

Brian

**Comment by tsizer** [comment]
Okay, I will do this later today.

I'm also attaching a screen shot of the way the svg image looked before I
edited some of the points.  (Don't remember if I sent it to you on Friday
-- but basically this was a "show stopper".)

Tania

On Mon, Jan 26, 2015 at 10:42 AM, Brian Duggan <notifications@github.com>
wrote:

> Hi Tania,
>
> Sure, please go ahead and make color and font adjustments however you
> think is appropriate, I'll plan to push this out later this week. (and ask
> for feedback at the same time)
>
> Brian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/pull/101#issuecomment-71502660>.
>



-- 
________________
*Tania Sizer*
Web Developer
UCAR/JOSS
P.O. Box 3000
Boulder, CO 80307
303-497-8684
tsizer@ucar.edu


*Joint Office for Science Supportwww.joss.ucar.edu
<http://www.joss.ucar.edu> *

**Pull request merged**
