### PR TITLE
Added conditional to contributors (if no author)

### PR DESCRIPTION
**Pull request by justgo129**

### CODE REVIEW

**Comment by justgo129** [comment]
Rationale: covers publications with zero contributors listed in GCIS in initial imports

**Comment by justgo129** [comment]
Merged #270.

**Comment by justgo129** [comment]
@rewolfe the triplestore on dev doesn't load a particular change.  Our debugging program no longer works:

Can't locate Virtuoso.pm in @INC (@INC contains: . /opt/perl5/common/libs/perl-5.16.3@gcis/lib/perl5/x86_64-linux /opt/perl5/common/libs/perl-5.16.3@gcis/lib/perl5 /opt/perl5/perls/perl-5.16.3/lib/site_perl/5.16.3/x86_64-linux /opt/perl5/perls/perl-5.16.3/lib/site_perl/5.16.3 /opt/perl5/perls/perl-5.16.3/lib/5.16.3/x86_64-linux /opt/perl5/perls/perl-5.16.3/lib/5.16.3) at ./importtest line 12.
BEGIN failed--compilation aborted at ./importtest line 12.

Does this have to do with credentials?

**Comment by rewolfe** [comment]
@justgo129 - It probably has to do with where you are running the script.  Virtuoso.pm has to be in that directory, or in one of the directories pointed to by @INC

**Comment by justgo129** [comment]
Good point.  That was it.  Closed #270.

**Pull request merged**
