### PR TITLE
Added possible fabio relation

### PR DESCRIPTION
**Pull request by justgo129**
@bduggan please do not merge until @zednis confirms whether or not these are appropriate additions.
http://vocab.ox.ac.uk/fabio#term_Book
http://vocab.ox.ac.uk/fabio#term_Chapter
Thanks!

### CODE REVIEW

**Comment by justgo129** [comment]
The 1st commit adds "fabio:Book" to the turtle for book.
The 2nd commits adds "fabio:Chapter" to the turtle for chapter.
(All added to enhance search-ability).

**Comment by justgo129** [comment]
We might able to do the same for fabio:Journal and fabio:JournalArticle as well.

**Comment by bduggan** [comment]
> @bduggan please do not merge until @zednis confirms whether or not these are appropriate additions.
@justgo129, please just submit pull requests that are ready to be merged.  Sounds like this is not, so I'll close it, but I'll reopen and merge when it's ready.

**Comment by zednis** [comment]
The changes proposed so far look good to me.  Please let me know when you have a completed set of proposed changes for me to review.

**Comment by justgo129** [comment]
Thanks, @zednis.  Other than for adding:
fabio:Report, fabio:Journal and fabio:JournalArticle
as objects to report, journal, and journal article, respectively, please consider this a complete list.  If adding those is all right with you, let's reopen the pull request.

**Comment by justgo129** [comment]
a gcis:Report, a fabio:Report .
a gcis:Journal, a fabio:Journal .
a gcis:AcademicArticle, a fabio:Article .

at the end of the respective turtles for report, journal, and article.

**Comment by zednis** [comment]
@justgo129 The 3 following updates you proposed in your comment also look good to me.

**Pull request merged**
